[[plugins]]
repo = 'vim-denops/denops.vim'
if = '''executable('deno') && v:version >= 901'''
# on_event = 'CursorHold'
hook_add = """
let g:denops_server_addr = '127.0.0.1:32123'
call job_start('deno run -A --no-check ' . dein#get('denops.vim').path . '/denops/@denops-private/cli.ts')
"""

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-filter-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-filter-sorter_rank'

[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
# hook_add = '''
# execute 'source ' . g:plugin_config_dir . '/hook/vim-lsp-settings.vim'
# '''

[[plugins]]
repo = 'shun/ddc-source-vim-lsp'



# hook の便利な使い方 https://qiita.com/delphinus/items/cd221a450fd23506e81a

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'Shougo/ddc-source-copilot'


# bufferからファイルを開く
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# syntax highlight
[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/ddc-source-omni'

