# hook の便利な使い方 https://qiita.com/delphinus/items/cd221a450fd23506e81a

# https://github.com/tpope/vim-surround
# https://qiita.com/takuyanin/items/5eb009e737a235e51ab2
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let NERDTreeShowHidden = 1
nmap <Leader>e :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-commentary'
hook_add = '''
    nmap <C-_> gcc
    vmap <C-_> gcc
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
depends = ['vim-airline']
hook_add = '''
let g:airline_theme = 'minimalist'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
let g:ctrlp_show_hidden = 1
let g:ctrlp_custom_ignore = {
    \ 'dir': '\v[\/](\.git|node_modules|target|build|vendor)$',
    \ 'file': '\v\.(exe|so|dll)$',
    \ 'link': 'some_bad_symbolic_links',
    \ }

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
'''

# 閉じ括弧を補完
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set signcolumn=yes
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
