[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']


[[plugins]]
repo  = 'preservim/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install'


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yml', 'yaml', 'docker-compose']
hook_add = '''
    let g:ansible_options = {'ignore_blank_lines': 0}
'''

