[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']


[[plugins]]
repo  = 'preservim/vim-markdown'
on_ft = ['markdown']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo  = 'phpactor/phpactor'
on_ft = ['php']
build = 'composer install --no-dev -o'

[[plugins]]
repo = 'kristijanhusak/deoplete-phpactor'
on_ft = ['php']

[[plugins]]
repo = 'camilledejoye/phpactor-mappings'
on_ft = ['php']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yml', 'yaml', 'docker-compose']
hook_add = '''
    let g:ansible_options = {'ignore_blank_lines': 0}
'''

[[plugins]]
repo = 'phpactor/ncm2-phpactor'
if = '!and(has("python3"), has("nvim"))'
on_ft = ['php']
depends = ['ncm2']
