#!/bin/sh

GIT_COMMITTER_NAME=$(git config user.name)
GIT_COMMITTER_EMAIL=$(git config user.email)

if [ "$GIT_AUTHOR_EMAIL" = "$GIT_COMMITTER_EMAIL" ]; then
    echo "Created by $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>"
else
    echo "Author: $GIT_AUTHOR_NAME <$GIT_AUTHOR_EMAIL>"
    echo "Committer: $GIT_COMMITTER_NAME <$GIT_COMMITTER_EMAIL>"
fi

echo
