alias ls='command ls --human-readable --group-directories-first --color=auto --ignore={NTUSER*,ntuser*}'

alias ll='ls -lF'
alias la='ls -AlF'
alias l='ls -CF'

if type nvim >/dev/null 2>&1; then
    export EDITOR=nvim
else
    export EDITOR=vim
fi

